services:
  backend:
    build: ./app
    container_name: habitat-api
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2
    working_dir: /app
    command: sh -c "chmod +x mvnw && ./mvnw spring-boot:run"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      API_SECRET_TOKEN: ${API_SECRET_TOKEN}
      ADMIN_EMAIL: ${ADMIN_EMAIL:juniorhabitatpe@gmail.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD: adminhabitat}
      ADMIN_NAME: ${ADMIN_NAME: Junior_Habitat}
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - target/
        - action: rebuild
          path: ./app/pom.xml